# Generated by Django 6.0.4 on 2026-05-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PROD', 'Production Record'), ('TRAN', 'Transfer/Logistics'), ('QUAL', 'Quality Control'), ('RECV', 'Market Received'), ('CERT', 'Certification/Approval')], max_length=4, verbose_name='Action Type')),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Transaction Hash (TxID)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('block_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Block Number')),
                ('payload', models.JSONField(blank=True, help_text='Data brief that sended to blockchain', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_logs', to='organizations.organization', verbose_name='Organization')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.pallet', verbose_name='Pallet')),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
