# Generated by Django 6.0.4 on 2026-05-11 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_code', models.CharField(db_index=True, editable=False, max_length=100, unique=True, verbose_name='Organization Code')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('organization_type', models.CharField(choices=[('PRODUCER', 'Producer Farm'), ('DISTRIBUTOR', 'Distributor Firm'), ('MARKET', 'Retail Market'), ('INSPECTOR', 'Inspection & Veterinary Agency')], max_length=20, verbose_name='Organization Type')),
                ('location', models.CharField(max_length=255, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='enlem')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='boylam')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='InspectionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('certificate_no', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inspector', models.ForeignKey(limit_choices_to={'organization_type': 'INSPECTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_certificates', to='organizations.organization')),
                ('producer', models.ForeignKey(limit_choices_to={'organization_type': 'PRODUCER'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_certificates', to='organizations.organization')),
            ],
        ),
    ]
