# Generated by Django 6.0.4 on 2026-05-21 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('master_qr_id', models.CharField(db_index=True, editable=False, max_length=100, unique=True, verbose_name='Pallet (Master)QR')),
                ('status', models.CharField(choices=[('IN_PRODUCTION', 'Preparing'), ('IN_TRANSIT', 'On Delivery'), ('AT_MARKET', 'On Retail'), ('FAULTY', 'Fault/Cancelled')], default='IN_PRODUCTION', max_length=20, verbose_name='Status')),
                ('vet_approval', models.BooleanField(default=False, verbose_name='Vet Approval')),
                ('is_quality_maintained', models.BooleanField(default=False, verbose_name='Quality/Temperature Ensured?')),
                ('departure_date', models.DateTimeField(blank=True, null=True, verbose_name='Çıkış Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_pallets', to='organizations.organization', verbose_name='Current Holder')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_pallets', to='organizations.organization', verbose_name='Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_qr_id', models.CharField(db_index=True, editable=False, max_length=100, unique=True, verbose_name='Paket QR')),
                ('feeding_type', models.IntegerField(choices=[(0, 'Organik'), (1, 'Gezen Tavuk'), (2, 'Kümes'), (3, 'Kafes')], default=2, verbose_name='Beslenme Türü')),
                ('laying_date', models.DateField(verbose_name='Yumurtlama Tarihi')),
                ('expiry_date', models.DateField(verbose_name='TETT')),
                ('capacity', models.IntegerField(choices=[(6, "6'lı"), (15, "15'li"), (30, "30'lu")], default=30, verbose_name='Kapasite')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='orders.pallet', verbose_name='Related Pallet')),
            ],
        ),
    ]
