# Generated by Django 6.0.4 on 2026-04-30 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Kurum Kodu (Public ID)')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('organization_type', models.CharField(choices=[('PRODUCER', 'Producer Farm'), ('DISTRIBUTOR', 'Distributor Firm'), ('MARKET', 'Retail Market'), ('INSPECTOR', 'Inspection & Veterinary Agency')], max_length=20, verbose_name='Organization Type')),
                ('location', models.CharField(max_length=255, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-posta adresi')),
                ('role', models.CharField(choices=[('ADMIN', 'System Manager'), ('ORG_ADMIN', 'Organization Manager'), ('STAFF', 'Staff'), ('VET', 'Veterinary')], default='STAFF', max_length=15, verbose_name='User Role')),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True, unique=True, verbose_name='Crypto Wallet Address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='orders.organization', verbose_name='Related Organization')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('certificate_no', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inspector', models.ForeignKey(limit_choices_to={'organization_type': 'INSPECTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_certificates', to='orders.organization')),
                ('producer', models.ForeignKey(limit_choices_to={'organization_type': 'PRODUCER'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_certificates', to='orders.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_qr_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Pallet (Master)QR')),
                ('status', models.CharField(choices=[('IN_PRODUCTION', 'Preparing'), ('IN_TRANSIT', 'On Delivery'), ('AT_MARKET', 'On Retail'), ('FAULTY', 'Fault/Cancelled')], default='IN_PRODUCTION', max_length=20, verbose_name='Status')),
                ('vet_approval', models.BooleanField(default=False, verbose_name='Vet Approval')),
                ('is_quality_maintained', models.BooleanField(default=True, verbose_name='Quality/Temperature Ensured?')),
                ('departure_date', models.DateTimeField(blank=True, null=True, verbose_name='Çıkış Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_pallets', to='orders.organization', verbose_name='Current Holder')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_pallets', to='orders.organization', verbose_name='Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_qr_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Paket QR')),
                ('feeding_type', models.IntegerField(choices=[(0, 'Organik'), (1, 'Gezen Tavuk'), (2, 'Kümes'), (3, 'Kafes')], default=2, verbose_name='Beslenme Türü')),
                ('laying_date', models.DateField(verbose_name='Yumurtlama Tarihi')),
                ('expiry_date', models.DateField(verbose_name='TETT')),
                ('capacity', models.IntegerField(choices=[(6, "6'lı"), (15, "15'li"), (30, "30'lu")], default=30, verbose_name='Kapasite')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='orders.pallet', verbose_name='Related Pallet')),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PROD', 'Production Record'), ('TRAN', 'Transfer/Logistics'), ('QUAL', 'Quality Control'), ('RECV', 'Market Received'), ('CERT', 'Certification/Approval')], max_length=4, verbose_name='Action Type')),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Transaction Hash (TxID)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('block_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Block Number')),
                ('payload', models.JSONField(blank=True, help_text='Data brief that sended to blockchain', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_logs', to='orders.organization', verbose_name='Organization')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.pallet', verbose_name='Pallet')),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
