# Generated by Django 6.0.4 on 2026-05-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marketorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('market',), name='unique_draft_order_per_market'),
        ),
    ]
