# Generated by Django 6.0.4 on 2026-04-18 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PROD', 'Production Record'), ('TRAN', 'Transfer/Logistics'), ('QUAL', 'Quality Control'), ('RECV', 'Market Received')], max_length=4, verbose_name='Action Type')),
                ('tx_hash', models.CharField(db_index=True, max_length=66, unique=True, verbose_name='Transaction Hash (TxID)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, help_text='Data brief that sended to blockchain', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.pallet', verbose_name='Pallet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
