# Generated by Django 6.0.4 on 2026-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='is_quality_maintained',
            field=models.BooleanField(default=False, verbose_name='Quality/Temperature Ensured?'),
        ),
    ]
