# Generated by Django 6.0.4 on 2026-05-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_marketorder_unique_draft_order_per_market'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='destination_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_pallets', to='organizations.organization', verbose_name='Hedef Market'),
        ),
    ]
