# Generated by Django 6.0.4 on 2026-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_blockchaintransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='feeding_type',
            field=models.CharField(choices=[('0', 'Organik'), ('1', 'Gezen Tavuk'), ('2', 'Kümes'), ('3', 'Kafes')], default='Kümes', max_length=20, verbose_name='Beslenme Türü'),
        ),
        migrations.AlterField(
            model_name='package',
            name='expiry_date',
            field=models.DateField(verbose_name='TETT'),
        ),
        migrations.AlterField(
            model_name='package',
            name='laying_date',
            field=models.DateField(verbose_name='Yumurtlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_qr_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Paket QR'),
        ),
    ]
