# Generated by Django 6.0.4 on 2026-04-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_package_feeding_type_alter_package_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Manager'), ('FARMER', 'Farmer'), ('DISTRIBUTOR', 'Distributor'), ('VET', 'Veterinary')], default='STAFF', max_length=15, verbose_name='User Role'),
        ),
    ]
