# Generated by Django 6.0.4 on 2026-05-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pallet_destination_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Cart / Building Order'), ('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Producer'), ('IN_PRODUCTION', 'Producer Preparing Pallet'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
