# Generated by Django 6.0.4 on 2026-04-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Manager'), ('FARMER', 'Farmer'), ('CLERK', 'Clerk'), ('DISTRIBUTOR', 'Distributor'), ('VET', 'Veterinary')], default='STAFF', max_length=15, verbose_name='User Role'),
        ),
    ]
