# Generated by Django 6.0.4 on 2026-04-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_code',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Kurum Kodu (Public ID)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Manager'), ('ORG_ADMIN', 'Organization Manager'), ('STAFF', 'Staff'), ('VET', 'Veterinary')], default='STAFF', max_length=15, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True, verbose_name='Crypto Wallet Address'),
        ),
    ]
