# Generated by Django 6.0.4 on 2026-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_organization_org_code_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_code',
            field=models.CharField(db_index=True, default='temp', max_length=50, unique=True, verbose_name='Kurum Kodu (Public ID)'),
            preserve_default=False,
        ),
    ]
