# Generated by Django 6.0.4 on 2026-04-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_organization_org_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('PRODUCER', 'Producer Farm'), ('DISTRIBUTOR', 'Distributor Firm'), ('MARKET', 'Retail Market'), ('INSPECTOR', 'Inspection & Veterinary Agency')], max_length=20, verbose_name='Organization Type'),
        ),
    ]
