# Generated by Django 6.0.4 on 2026-04-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_organization_organization_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('certificate_no', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inspector', models.ForeignKey(limit_choices_to={'organization_type': 'INSPECTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_certificates', to='orders.organization')),
                ('producer', models.ForeignKey(limit_choices_to={'organization_type': 'PRODUCER'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_certificates', to='orders.organization')),
            ],
        ),
    ]
