# Generated by Django 6.0.4 on 2026-04-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_inspectioncertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchaintransaction',
            name='block_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Block Number'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_logs', to='orders.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='action_type',
            field=models.CharField(choices=[('PROD', 'Production Record'), ('TRAN', 'Transfer/Logistics'), ('QUAL', 'Quality Control'), ('RECV', 'Market Received'), ('CERT', 'Certification/Approval')], max_length=4, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Transaction Hash (TxID)'),
        ),
    ]
