# Generated by Django 6.0.4 on 2026-04-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_blockchaintransaction_block_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.pallet', verbose_name='Pallet'),
        ),
    ]
