# Generated by Django 6.0.4 on 2026-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_blockchaintransaction_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='feeding_type',
            field=models.CharField(choices=[('0', 'Organik'), ('1', 'Gezen Tavuk'), ('2', 'Kümes'), ('3', 'Kafes')], default=2, max_length=20, verbose_name='Beslenme Türü'),
        ),
    ]
