# Generated by Django 6.0.4 on 2026-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_package_feeding_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='capacity',
            field=models.IntegerField(choices=[(6, "6'lı"), (15, "15'li"), (30, "30'lu")], default=30, verbose_name='Kapasite'),
        ),
        migrations.AlterField(
            model_name='package',
            name='feeding_type',
            field=models.IntegerField(choices=[(0, 'Organik'), (1, 'Gezen Tavuk'), (2, 'Kümes'), (3, 'Kafes')], default=2, verbose_name='Beslenme Türü'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Çıkış Tarihi'),
        ),
    ]
